title: 'asce-21.github.io'
description: "Personal blog about cybersecurity"
baseurl: "/"
url: "https://asce-21.github.io"

header_pages:
  - index.md
  - achievements.md
  - about.md
  - contact.md

style: dark

footer: 'follow on <a href="https://twitter.com/sanam_dhar">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
